# Generated by Django 5.0.4 on 2024-04-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='floor',
            field=models.IntegerField(default=1),
        ),
    ]
